"""initial schema

Revision ID: 0935df4c3e73
Revises: 
Create Date: 2026-08-10 07:54:01.814015
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The portable column types resolve per dialect at migration time: JSONBType becomes
# JSONB on PostgreSQL and JSON elsewhere, VectorType becomes pgvector's vector(384) on
# PostgreSQL and TEXT elsewhere. Autogenerate renders them by name, so the module must
# be importable here.
import app.db.types


revision: str = '0935df4c3e73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must exist before any vector column is created. Guarded by dialect so the
    # same migration runs against SQLite in development and CI.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_systems',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('culture', sa.String(length=160), nullable=True),
    sa.Column('calendar_kind', sa.String(length=40), nullable=False),
    sa.Column('epoch_description', sa.Text(), nullable=True),
    sa.Column('epoch_rd', sa.Integer(), nullable=True),
    sa.Column('months_per_year', sa.Integer(), nullable=True),
    sa.Column('supports_conversion', sa.Boolean(), nullable=False),
    sa.Column('conversion_caveats', sa.Text(), nullable=True),
    sa.Column('active_from_year', sa.Integer(), nullable=True),
    sa.Column('active_to_year', sa.Integer(), nullable=True),
    sa.Column('references', app.db.types.JSONBType(), nullable=False),
    sa.Column('attributes', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_systems'))
    )
    with op.batch_alter_table('calendar_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_systems_key'), ['key'], unique=True)

    op.create_table('datasets',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('attributes', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_key'), ['key'], unique=True)

    op.create_table('historical_sources',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('alternate_titles', app.db.types.JSONBType(), nullable=False),
    sa.Column('tradition', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.Column('script', sa.String(length=60), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('composition_earliest_year', sa.Integer(), nullable=True),
    sa.Column('composition_latest_year', sa.Integer(), nullable=True),
    sa.Column('dating_note', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_citation', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('reliability', sa.String(length=40), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('attributes', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historical_sources')),
    sa.UniqueConstraint('slug', name='uq_historical_sources_slug')
    )
    with op.batch_alter_table('historical_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_sources_slug'), ['slug'], unique=False)
        batch_op.create_index('ix_historical_sources_tradition', ['tradition'], unique=False)

    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELLED', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('result', app.db.types.JSONBType(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index('ix_jobs_status_priority', ['status', 'priority', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_target_id'), ['target_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'USER', 'RESEARCHER', 'MODERATOR', 'ADMIN', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyses_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('astronomical_events',
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('julian_day', sa.Float(), nullable=True),
    sa.Column('calendar_used', sa.String(length=20), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('visibility_regions', app.db.types.JSONBType(), nullable=False),
    sa.Column('visibility_uncertainty', sa.Text(), nullable=True),
    sa.Column('delta_t_seconds', sa.Float(), nullable=True),
    sa.Column('bodies', app.db.types.JSONBType(), nullable=False),
    sa.Column('constellation', sa.String(length=80), nullable=True),
    sa.Column('separation_degrees', sa.Float(), nullable=True),
    sa.Column('is_computed', sa.Boolean(), nullable=False),
    sa.Column('computation_engine', sa.String(length=120), nullable=True),
    sa.Column('accuracy_note', sa.Text(), nullable=True),
    sa.Column('historical_source_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['historical_source_id'], ['historical_sources.id'], name=op.f('fk_astronomical_events_historical_source_id_historical_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_astronomical_events'))
    )
    with op.batch_alter_table('astronomical_events', schema=None) as batch_op:
        batch_op.create_index('ix_astro_events_jd', ['julian_day'], unique=False)
        batch_op.create_index('ix_astro_events_type_year', ['event_type', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_astronomical_events_designation'), ['designation'], unique=False)
        batch_op.create_index(batch_op.f('ix_astronomical_events_julian_day'), ['julian_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_astronomical_events_year'), ['year'], unique=False)

    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'REGISTER', 'ANALYSIS_CREATED', 'ANALYSIS_VIEWED', 'ANALYSIS_DELETED', 'ANALYSIS_EXPORTED', 'ANALYSIS_SHARED', 'UPLOAD_RECEIVED', 'UPLOAD_REJECTED', 'URL_FETCHED', 'SETTINGS_UPDATED', 'ROLE_CHANGED', 'USER_DEACTIVATED', 'PROMPT_UPDATED', 'DATASET_UPDATED', 'RATE_LIMITED', 'ADMIN_ACTION', 'SECURITY_EVENT', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('detail', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('collections',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_collections_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_owner_id'), ['owner_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('tradition', sa.String(length=40), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('embedding', app.db.types.VectorType(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('historical_source_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['historical_source_id'], ['historical_sources.id'], name=op.f('fk_knowledge_chunks_historical_source_id_historical_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_chunks_kind', ['kind', 'source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_source_key'), ['source_key'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('oauth_identities',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('raw_profile', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_oauth_provider_subject')
    )
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_identities_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('instruction_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_prompt_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('agent_name', 'version', name='uq_prompt_templates_agent_version')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_agent_name'), ['agent_name'], unique=False)

    op.create_table('search_history',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('filters', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('ix_search_history_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_user_id'), ['user_id'], unique=False)

    op.create_table('source_passages',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('reference_label', sa.String(length=160), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('translation_credit', sa.String(length=300), nullable=True),
    sa.Column('themes', app.db.types.JSONBType(), nullable=False),
    sa.Column('astronomical_content', sa.Boolean(), nullable=False),
    sa.Column('prophetic_content', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['historical_sources.id'], name=op.f('fk_source_passages_source_id_historical_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_passages'))
    )
    with op.batch_alter_table('source_passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_passages_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_source_passages_source_ref', ['source_id', 'reference_label'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', app.db.types.JSONBType(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('tags',
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tags_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_tags_owner_slug')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=False)

    op.create_table('uploads',
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('detected_mime_type', sa.String(length=160), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'SCANNING', 'EXTRACTING', 'READY', 'REJECTED', 'FAILED', name='uploadstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_metadata', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_uploads_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads')),
    sa.UniqueConstraint('owner_id', 'sha256', name='uq_uploads_owner_sha256')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_sha256'), ['sha256'], unique=False)
        batch_op.create_index('ix_uploads_status_created', ['status', 'created_at'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('default_output_language', sa.String(length=16), nullable=False),
    sa.Column('show_advanced_by_default', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('preferences', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('documents',
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_kind', sa.Enum('PASTED_TEXT', 'FILE_UPLOAD', 'URL', 'API', name='sourcekind', native_enum=False, length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('detected_language_confidence', sa.Float(), nullable=True),
    sa.Column('detected_script', sa.String(length=40), nullable=True),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_metadata', app.db.types.JSONBType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_documents_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_documents_upload_id_uploads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_documents_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)

    op.create_table('analyses',
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='analysisstatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('anonymous_token_hash', sa.String(length=64), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('translation_applied', sa.Boolean(), nullable=False),
    sa.Column('source_identification', app.db.types.JSONBType(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('options', app.db.types.JSONBType(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_stages', app.db.types.JSONBType(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', app.db.types.JSONBType(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_analysis_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('overall_confidence IS NULL OR (overall_confidence >= 0 AND overall_confidence <= 1)', name=op.f('ck_analyses_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_analyses_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_analyses_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_analysis_id'], ['analyses.id'], name=op.f('fk_analyses_parent_analysis_id_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_analyses_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_anonymous_token_hash'), ['anonymous_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_analyses_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)
        batch_op.create_index('ix_analyses_status_created', ['status', 'created_at'], unique=False)

    op.create_table('agent_runs',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('input_summary', app.db.types.JSONBType(), nullable=False),
    sa.Column('output_summary', app.db.types.JSONBType(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_agent_runs_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_agent_runs_analysis_seq', ['analysis_id', 'sequence'], unique=False)

    op.create_table('analysis_embeddings',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('embedding', app.db.types.VectorType(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_embeddings_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_analysis_embeddings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_embeddings'))
    )
    with op.batch_alter_table('analysis_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_embeddings_analysis_id'), ['analysis_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_embeddings_owner_id'), ['owner_id'], unique=False)

    op.create_table('analysis_tags',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_tags_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_analysis_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'tag_id', name=op.f('pk_analysis_tags'))
    )
    op.create_table('claims',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=False),
    sa.Column('claim_type', sa.Enum('SOURCE_TEXT', 'VERIFIED_HISTORY', 'ASTRONOMICAL_CALCULATION', 'TEXTUAL_ANALYSIS', 'TRADITIONAL_INTERPRETATION', 'SCHOLARLY_INTERPRETATION', 'AI_HYPOTHESIS', 'UNCERTAIN', name='claimtype', native_enum=False, length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_basis', sa.String(length=500), nullable=True),
    sa.Column('produced_by', sa.String(length=60), nullable=False),
    sa.Column('engine', sa.String(length=120), nullable=True),
    sa.Column('algorithm_reference', sa.String(length=300), nullable=True),
    sa.Column('supports_claim_id', sa.String(), nullable=True),
    sa.Column('contradicts_claim_id', sa.String(), nullable=True),
    sa.Column('text_span_start', sa.Integer(), nullable=True),
    sa.Column('text_span_end', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_claims_confidence_range')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_claims_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contradicts_claim_id'], ['claims.id'], name=op.f('fk_claims_contradicts_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supports_claim_id'], ['claims.id'], name=op.f('fk_claims_supports_claim_id_claims'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_claims_analysis_type', ['analysis_id', 'claim_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_section'), ['section'], unique=False)

    op.create_table('collection_analyses',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_collection_analyses_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_analyses_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'analysis_id', name=op.f('pk_collection_analyses'))
    )
    op.create_table('entities',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'PLACE', 'EMPIRE', 'NATION', 'RELIGION', 'CULTURE', 'DEITY', 'DATE', 'CALENDAR', 'ASTRONOMICAL_OBJECT', 'CONSTELLATION', 'PLANET', 'STAR', 'COMET', 'ECLIPSE', 'METEOR_SHOWER', 'MOON_PHASE', 'ZODIAC_SIGN', 'SACRED_NUMBER', 'SYMBOL', 'PROPHECY', 'PREDICTION', 'HISTORICAL_EVENT', 'ARTIFACT', 'TEXT_WORK', 'OTHER', name='entitytype', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=True),
    sa.Column('aliases', app.db.types.JSONBType(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('identification_confidence', sa.Float(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('mentions', app.db.types.JSONBType(), nullable=False),
    sa.Column('earliest_year', sa.Integer(), nullable=True),
    sa.Column('latest_year', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('linked_source_id', sa.String(), nullable=True),
    sa.Column('linked_astronomical_event_id', sa.String(), nullable=True),
    sa.Column('attributes', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_entities_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_astronomical_event_id'], ['astronomical_events.id'], name=op.f('fk_entities_linked_astronomical_event_id_astronomical_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_source_id'], ['historical_sources.id'], name=op.f('fk_entities_linked_source_id_historical_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_entities_analysis_type', ['analysis_id', 'entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_name'), ['name'], unique=False)

    op.create_table('reports',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sections', app.db.types.JSONBType(), nullable=False),
    sa.Column('timeline', app.db.types.JSONBType(), nullable=False),
    sa.Column('confidence_summary', app.db.types.JSONBType(), nullable=False),
    sa.Column('further_reading', app.db.types.JSONBType(), nullable=False),
    sa.Column('reasoning_trace', app.db.types.JSONBType(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('generator_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_reports_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('analysis_id', 'version', name='uq_reports_analysis_version')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('shares',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('allow_export', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_shares_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_shares_created_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares'))
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_token_hash'), ['token_hash'], unique=True)

    op.create_table('references',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('historical_source_id', sa.String(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', app.db.types.JSONBType(), nullable=False),
    sa.Column('publication', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('locator', sa.String(length=200), nullable=True),
    sa.Column('reference_kind', sa.String(length=40), nullable=False),
    sa.Column('reliability', sa.String(length=40), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_references_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_references_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['historical_source_id'], ['historical_sources.id'], name=op.f('fk_references_historical_source_id_historical_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_references'))
    )
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.create_index('ix_references_analysis', ['analysis_id', 'ordering'], unique=False)
        batch_op.create_index(batch_op.f('ix_references_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # IVFFlat indexes for cosine similarity. `lists` is tuned for a corpus in the
        # thousands; raise it towards sqrt(rows) as the corpus grows. Without an index
        # pgvector still returns correct results, just with a sequential scan.
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_embedding "
            "ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops) "
            "WITH (lists = 100)"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_analysis_embeddings_embedding "
            "ON analysis_embeddings USING ivfflat (embedding vector_cosine_ops) "
            "WITH (lists = 50)"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_analysis_embeddings_embedding")
        op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_references_analysis_id'))
        batch_op.drop_index('ix_references_analysis')

    op.drop_table('references')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_token_hash'))
        batch_op.drop_index(batch_op.f('ix_shares_analysis_id'))

    op.drop_table('shares')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_analysis_id'))

    op.drop_table('reports')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_name'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_name'))
        batch_op.drop_index('ix_entities_analysis_type')
        batch_op.drop_index(batch_op.f('ix_entities_analysis_id'))

    op.drop_table('entities')
    op.drop_table('collection_analyses')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_section'))
        batch_op.drop_index('ix_claims_analysis_type')
        batch_op.drop_index(batch_op.f('ix_claims_analysis_id'))

    op.drop_table('claims')
    op.drop_table('analysis_tags')
    with op.batch_alter_table('analysis_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_embeddings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_embeddings_analysis_id'))

    op.drop_table('analysis_embeddings')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_runs_analysis_seq')
        batch_op.drop_index(batch_op.f('ix_agent_runs_analysis_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_analyses_status_created')
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_owner_id'))
        batch_op.drop_index('ix_analyses_owner_created')
        batch_op.drop_index(batch_op.f('ix_analyses_document_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_anonymous_token_hash'))

    op.drop_table('analyses')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index('ix_documents_owner_created')
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    op.drop_table('user_settings')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index('ix_uploads_status_created')
        batch_op.drop_index(batch_op.f('ix_uploads_sha256'))
        batch_op.drop_index(batch_op.f('ix_uploads_owner_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('source_passages', schema=None) as batch_op:
        batch_op.drop_index('ix_source_passages_source_ref')
        batch_op.drop_index(batch_op.f('ix_source_passages_source_id'))

    op.drop_table('source_passages')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_user_id'))
        batch_op.drop_index('ix_search_history_user_created')

    op.drop_table('search_history')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_agent_name'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_identities_user_id'))

    op.drop_table('oauth_identities')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_source_key'))
        batch_op.drop_index('ix_knowledge_chunks_kind')

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_owner_id'))

    op.drop_table('collections')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('astronomical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_astronomical_events_year'))
        batch_op.drop_index(batch_op.f('ix_astronomical_events_julian_day'))
        batch_op.drop_index(batch_op.f('ix_astronomical_events_designation'))
        batch_op.drop_index('ix_astro_events_type_year')
        batch_op.drop_index('ix_astro_events_jd')

    op.drop_table('astronomical_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_target_id'))
        batch_op.drop_index('ix_jobs_status_priority')
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('historical_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_historical_sources_tradition')
        batch_op.drop_index(batch_op.f('ix_historical_sources_slug'))

    op.drop_table('historical_sources')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_key'))

    op.drop_table('datasets')
    with op.batch_alter_table('calendar_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_systems_key'))

    op.drop_table('calendar_systems')
    # ### end Alembic commands ###
