"""astronomical dating usage ledger

Revision ID: 75875e51f574
Revises: 48cd064670a4
Create Date: 2026-08-29 15:14:57.678058

One row per astronomical dating search, rather than a counter column on `users`.

The free allowance is five searches for the life of the account, so the question the
application asks is `COUNT(*) WHERE user_id = ?` — no period boundary, no reset, and
nothing that needs a scheduled job. That last point decided it: this deployment runs
with no background worker by design (docs/GO_LIVE.md), so a monthly quota would have
been a quota that silently never reset.

A counter would also have been a lossy version of the same data. These rows record which
analysis each search produced and when, which is what makes a support question about
someone's allowance answerable.

`analysis_id` is nullable with ON DELETE SET NULL: deleting an analysis must not
retroactively refund the search that produced it, and must not fail because a usage row
points at it.

Additive only. No existing table is touched, so the downgrade is a clean drop and
`ClaimType.ASTRONOMICAL_DATING_CANDIDATE`, added in the same change, needs no migration
at all — the column is `Enum(native_enum=False)`, which is a plain VARCHAR with no check
constraint enumerating the members.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75875e51f574"
down_revision: str | None = "48cd064670a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "astronomical_dating_usage",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=True),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_astronomical_dating_usage_analysis_id_analyses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_astronomical_dating_usage_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_astronomical_dating_usage")),
    )
    with op.batch_alter_table("astronomical_dating_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_astronomical_dating_usage_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_astronomical_dating_usage_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_dating_usage_user_created", ["user_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("astronomical_dating_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_dating_usage_user_created")
        batch_op.drop_index(batch_op.f("ix_astronomical_dating_usage_user_id"))
        batch_op.drop_index(batch_op.f("ix_astronomical_dating_usage_analysis_id"))

    op.drop_table("astronomical_dating_usage")
    # ### end Alembic commands ###
