/**
 * Presentation rules for claim types.
 *
 * This table is the UI half of the epistemic contract. The backend decides *what* a
 * claim is; this decides how it looks, and the two must never drift. Every surface —
 * report, export preview, timeline, search result — renders through here rather than
 * inventing its own styling, so a hypothesis can never accidentally be shown with the
 * visual weight of a verified fact.
 */

import type { ClaimType } from "./types";

export interface ClaimStyle {
  label: string;
  short: string;
  description: string;
  /** Tailwind classes for the badge. */
  badge: string;
  /** Left border used on the claim card. */
  border: string;
  /** Icon glyph. Paired with text, never used alone — colour and shape are not enough. */
  icon: string;
  /** True for claim types that constitute evidence rather than commentary. */
  isEvidence: boolean;
}

export const CLAIM_STYLES: Record<ClaimType, ClaimStyle> = {
  source_text: {
    label: "Source text",
    short: "From your text",
    description:
      "Quoted verbatim from the text you submitted. No interpretation has been added.",
    badge:
      "bg-ink-100 text-ink-800 border-ink-300 dark:bg-ink-800 dark:text-ink-200 dark:border-ink-600",
    border: "border-l-ink-500",
    icon: "❝",
    isEvidence: true,
  },
  verified_history: {
    label: "Verified history",
    short: "Established",
    description:
      "Supported by the historical record and citable. “Verified” means well attested in scholarship, not beyond all dispute.",
    badge:
      "bg-verdigris-50 text-verdigris-900 border-verdigris-300 dark:bg-verdigris-950 dark:text-verdigris-200 dark:border-verdigris-700",
    border: "border-l-verdigris-600",
    icon: "✓",
    isEvidence: true,
  },
  astronomical_calculation: {
    label: "Calculation",
    short: "Calculated",
    description:
      "Computed by the platform's ephemeris and calendar engines. Reproducible, and reported with the accuracy of the algorithm that produced it.",
    badge:
      "bg-lapis-50 text-lapis-900 border-lapis-300 dark:bg-lapis-950 dark:text-lapis-200 dark:border-lapis-700",
    border: "border-l-lapis-700",
    icon: "∑",
    isEvidence: true,
  },
  textual_analysis: {
    label: "Text analysis",
    short: "Text analysis",
    description:
      "An observation about the text itself — its language, structure or vocabulary.",
    badge:
      "bg-reed-50 text-reed-900 border-reed-300 dark:bg-reed-950 dark:text-reed-200 dark:border-reed-700",
    border: "border-l-reed-700",
    icon: "❡",
    isEvidence: false,
  },
  traditional_interpretation: {
    label: "Tradition holds",
    short: "Tradition",
    description:
      "What a religious or cultural tradition has historically understood this to mean. Reported as that tradition's position, not endorsed as fact.",
    badge:
      "bg-gold-50 text-gold-900 border-gold-300 dark:bg-gold-950 dark:text-gold-200 dark:border-gold-700",
    border: "border-l-gold-600",
    icon: "☽",
    isEvidence: false,
  },
  scholarly_interpretation: {
    label: "Scholars argue",
    short: "Scholarship",
    description:
      "A position argued in academic literature. Where scholars disagree, the disagreement is reported rather than resolved.",
    badge:
      "bg-plum-50 text-plum-900 border-plum-300 dark:bg-plum-950 dark:text-plum-200 dark:border-plum-700",
    border: "border-l-plum-600",
    icon: "§",
    isEvidence: false,
  },
  ai_hypothesis: {
    label: "AI hypothesis",
    short: "AI conjecture",
    description:
      "Generated by the language model. A suggestion for you to evaluate, not evidence, and it may be wrong. Confidence is capped by design.",
    badge:
      "bg-terra-50 text-terra-900 border-terra-400 dark:bg-terra-950 dark:text-terra-200 dark:border-terra-600",
    border: "border-l-terra-600",
    icon: "?",
    isEvidence: false,
  },
  uncertain: {
    label: "Unresolved",
    short: "Unknown",
    description: "Genuinely undetermined on the available evidence.",
    badge:
      "bg-ink-50 text-ink-700 border-ink-300 dark:bg-ink-900 dark:text-ink-300 dark:border-ink-700",
    border: "border-l-ink-400",
    icon: "—",
    isEvidence: false,
  },
};

export function claimStyle(type: ClaimType): ClaimStyle {
  return CLAIM_STYLES[type] ?? CLAIM_STYLES.uncertain;
}

export function confidenceBand(value: number): string {
  if (value >= 0.85) return "very high";
  if (value >= 0.7) return "high";
  if (value >= 0.5) return "moderate";
  if (value >= 0.3) return "low";
  return "very low";
}

export function confidenceColor(value: number): string {
  if (value >= 0.7) return "bg-verdigris-600";
  if (value >= 0.5) return "bg-gold-500";
  if (value >= 0.3) return "bg-terra-500";
  return "bg-crimson-500";
}

/** Section keys in the order the report specifies. */
export const SECTION_ORDER = [
  "executive_summary",
  "original_text",
  "detected_language",
  "translation",
  "source_identification",
  "historical_context",
  "astronomical_references",
  "calendar_conversion",
  "timeline",
  "key_entities",
  "symbolism",
  "traditional_interpretations",
  "scholarly_views",
  "alternative_interpretations",
  "evidence",
  "confidence_ratings",
  "references",
  "further_reading",
] as const;

/** Human labels for entity types, for the entity table's grouping. */
export const ENTITY_TYPE_LABELS: Record<string, string> = {
  person: "People",
  place: "Places",
  empire: "Empires",
  nation: "Nations",
  religion: "Religions",
  culture: "Cultures",
  deity: "Deities",
  date: "Dates",
  calendar: "Calendars",
  astronomical_object: "Celestial objects",
  constellation: "Constellations",
  planet: "Planets",
  star: "Stars",
  comet: "Comets",
  eclipse: "Eclipses",
  meteor_shower: "Meteor showers",
  moon_phase: "Moon phases",
  zodiac_sign: "Zodiac signs",
  sacred_number: "Sacred numbers",
  symbol: "Symbols",
  prophecy: "Prophecies",
  prediction: "Predictions",
  historical_event: "Historical events",
  artifact: "Artifacts",
  text_work: "Texts",
  other: "Other",
};

export function entityTypeLabel(type: string): string {
  return ENTITY_TYPE_LABELS[type] ?? type.replace(/_/g, " ");
}

/** Format an astronomical year for display, converting out of astronomical numbering. */
export function formatYear(year: number): string {
  return year <= 0 ? `${1 - year} BCE` : `${year} CE`;
}

export function formatDuration(ms?: number | null): string {
  if (ms == null) return "—";
  if (ms < 1000) return `${ms} ms`;
  return `${(ms / 1000).toFixed(1)} s`;
}
